; <?php /*

; Use the values below to specify alternate environment variables
; that Elefant should look at for each setting. For example, to look
; for the database host in MYSQL_HOST, change the following:
;
; ELEFANT_DB_HOST = MYSQL_HOST
;
; Leave the defaults in the form `ENV_VAR = ENV_VAR`.

ELEFANT_DB_DRIVER = ELEFANT_DB_DRIVER
ELEFANT_DB_FILE = ELEFANT_DB_FILE
ELEFANT_DB_HOST = ELEFANT_DB_HOST
ELEFANT_DB_NAME = ELEFANT_DB_NAME
ELEFANT_DB_USER = ELEFANT_DB_USER
ELEFANT_DB_PASS = ELEFANT_DB_PASS
ELEFANT_TIMEZONE = ELEFANT_TIMEZONE
ELEFANT_UPDATES = ELEFANT_UPDATES
ELEFANT_SITE_KEY = ELEFANT_SITE_KEY
ELEFANT_SESSION_NAME = ELEFANT_SESSION_NAME
ELEFANT_SESSION_HANDLER = ELEFANT_SESSION_HANDLER
ELEFANT_SESSION_DOMAIN = ELEFANT_SESSION_DOMAIN
ELEFANT_SESSION_DURATION = ELEFANT_SESSION_DURATION

; */